import { StyledButton } from "../styled/button.slint";

export component Feedback {
    callback close();
    in property <length> top;
    in property <string> out-text: "tests";
    in property <bool> is-open;

    property <length> offset: top - 5px;

    Rectangle {
        y: is-open ? 0 - offset : top;
        width: self.preferred-width;
        height: self.preferred-height;
        border-width: 2px;
        border-color: silver;
        border-radius: 5px;
        background: black;
        clip: true;

        HorizontalLayout {
            padding-left: 20px;
            padding-right: 20px;
            padding-top: 7.5px;
            padding-bottom: 10px;
            spacing: 10px;

            VerticalLayout {
                alignment: center;

                Text {
                    text: out-text;
                    font-size: 16px;
                    color: lime;
                    min-width: 150px;
                }
            }
            
            StyledButton {
                button-text: "X";
                button-width: 0px;

                button-click => { close() }
            }
        }
    }
}