export component StyledStack inherits Rectangle {
    in property <length> stack-spacing : 0px;
    in property <LayoutAlignment> stack-align : start;
    in property <[length]> stack-padding : [0px, 0px, 0px, 0px];

    background: black;

    VerticalLayout {
        alignment: stack-align;
        spacing: stack-spacing;
        padding-top: stack-padding[0];
        padding-left: stack-padding[1];
        padding-bottom: stack-padding[2];
        padding-right: stack-padding[3];

        @children
    }
}

export component StyledStream inherits Rectangle {
    in property <length> stack-spacing : 0px;
    in property <LayoutAlignment> stack-align : start;
    in property <[length]> stack-padding : [0px, 0px, 0px, 0px];

    width: self.preferred-width;
    background: black;

    HorizontalLayout {
        alignment: stack-align;
        spacing: stack-spacing;
        padding-top: stack-padding[0];
        padding-left: stack-padding[1];
        padding-bottom: stack-padding[2];
        padding-right: stack-padding[3];

        @children
    }
}