import { HorizontalBox , Button, LineEdit, TextEdit} from "std-widgets.slint";

export component LabeledInput inherits Rectangle {
    in property <bool> required: false;
    in property <string> label: "label";
    in property <length> label-width: 0;
    in property <string> input-placeholder : "";
    in property <length> input-width: label-width * 2;
    
    out property <string> value: textinput.text;

    property <string> label-name: required ? label + "*" : label;

    width: self.preferred-width;
    height: self.preferred-height;
    border-width: 1px;
    border-color: silver;
    border-radius: 5px;
    background: rgb(50, 50, 75);

    HorizontalLayout {

        VerticalLayout {
            alignment: center;
            padding-left: 10px;

            Text {
                min-width: max(self.preferred-width, label-width);
                text: label-name;
            }
        }
        
        textinput := LineEdit {
            placeholder-text: input-placeholder;
            width: max(self.preferred-width, input-width);
        }
    }
}

export component LabeledText inherits Rectangle {
    in property <string> label : "label";
    in property <length> area-width: 0;
    in property <bool> required: false;

    out property <string> value: textarea.text;
    
    width: self.preferred-width;
    height: self.preferred-height;

    VerticalLayout {

        VerticalLayout {
            padding-left: 10px;

            Text {
                text: label;
                font-size: 13px;
                height: self.preferred-height * 1.2;
            }
        }

        Rectangle {
            border-width: 1px;
            border-color: silver;
            border-radius: 5px;
            background: rgb(50, 50, 75);

            VerticalLayout {
                textarea := TextEdit {
                    width: area-width + 10px;
                    height: area-width / 2;
                }
            }
        }
    }
}