import { HorizontalBox , Button, LineEdit} from "std-widgets.slint";

export component LabeledInput inherits Rectangle {
    in property <string> label : "label";
    in property <length> label-width: 0;
    in property <string> input-placeholder : "";
    in property <length> input-width: label-width * 2;
    
    out property <string> value: textinput.text;

    width: self.preferred-width;
    height: self.preferred-height;
    border-width: 1px;
    border-color: silver;
    border-radius: 5px;
    background: rgb(50, 50, 75);

    HorizontalBox {
        spacing: 0;
        padding: 0;

        Button {
            min-width: max(self.preferred-width, label-width);
            text: label;
            clicked => {textinput.focus()}
        }
        
        textinput := LineEdit {
            placeholder-text: input-placeholder;
            width: max(self.preferred-width, input-width);
        }
    }
}