import { TabWidget, LineEdit } from "std-widgets.slint";

import { StyledStack, StyledStream } from "layouts/stacks.slint";

import { StyledButton } from "styled/button.slint";
import { LabeledInput } from "styled/labeled-input.slint";
import { Break } from "styled/break.slint";

import { Feedback } from "components/feedback.slint";
import { NavBar } from "components/navbar.slint";

export component AppWindow inherits Window {
    default-font-family: "monospace";
    default-font-size: 18px;
    background: transparent;

    callback set_feedback(string);
    callback close_feedback();
    in property <string> feedback-out: "Feedback";
    in property <bool> is-open: false;

    StyledStream {
        stack-bg: rgb(50, 50, 75);
        stack-spacing: 20px;
        stack-padding: [20px, 20px, 20px, 20px];
        border-radius: 20px;

        NavBar {
            action-1 => {set_feedback("feed")}
            action-2 => {set_feedback("feed 2")}
            action-3 => {set_feedback("feed 3")}

            username: "Jace";
        }

        Break {
            color: silver;
            thickness: 1px;
        }

        StyledStack {
            stack-bg: rgb(0, 0, 0, 0.2);
            
            TabWidget {
                Tab {
                    title: "Tab 0";
                    StyledStack {}
                }
                Tab {
                    title: "Tab 1";
                    StyledStack {
                        stack-spacing: 10px;
                        stack-padding: [15px, 20px, 15px, 20px];

                        LabeledInput {}
                        LabeledInput {}
                        LabeledInput {}

                    }
                }
                Tab {
                    title: "Tab 2";
                    StyledStack {}
                }
            }
        }
    }

    Feedback {
        is-open: is-open;
        out-text: feedback-out;
        top: parent.height / 2;
        close => { close-feedback() }
    }
}

